# Generated by Django 4.2.6 on 2024-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(),
        ),
    ]
