# Generated by Django 4.2.6 on 2024-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingGame', '0003_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomWinningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wining_num', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('start_datetime',),
            },
        ),
    ]
