# Generated by Django 4.2.6 on 2024-05-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=5.3)),
                ('conversion_pkr', models.FloatField(default=1)),
                ('conversion_trx', models.FloatField(default=0.26)),
                ('conversion_usdt', models.FloatField(default=279)),
                ('minimu_deposit', models.FloatField(default=200)),
                ('max_deposit', models.FloatField(default=1000000)),
                ('minimum_withdrawal', models.FloatField(default=200)),
                ('maximum_withdrawal', models.FloatField(default=1000000)),
                ('minimum_withdrawal_trx', models.FloatField(default=10)),
                ('maximum_withdrawal_trx', models.FloatField(default=1000000)),
                ('minimum_withdrawal_usdt', models.FloatField(default=2)),
                ('maximum_withdrawal_usdt', models.FloatField(default=1000000)),
                ('crypto_fee', models.FloatField(default=5)),
                ('normal_fee', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_limit', models.FloatField(default=0)),
                ('account_address', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_network', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_limit', models.FloatField(default=0)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('withdrawal_currency', models.CharField(default='PKR', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('price_paid', models.DecimalField(decimal_places=5, max_digits=20)),
                ('price_currency', models.CharField(default='PKR', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gameId', models.CharField(max_length=255, unique=True)),
                ('crypto_address', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('level_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_1', to=settings.AUTH_USER_MODEL)),
                ('level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_2', to=settings.AUTH_USER_MODEL)),
                ('level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_3', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('deposit_currency', models.CharField(default='PKR', max_length=255)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('deposit_reciept', models.ImageField(blank=True, null=True, upload_to='deposit_reciepts')),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.depositaccounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bonus_currency', models.CharField(default='PKR', max_length=255)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_giver', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
